FROM python:3.9-slim

COPY frontend.py /app/frontend.py
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app

CMD ["python", "frontend.py"]
