version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"

  ebpf:
    build:
      context: ./ebpf
      dockerfile: Dockerfile_ebpf
    privileged: true

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    depends_on:
      - backend
      - ebpf

volumes:
  grafana_data:
