version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"
    depends_on:
      - ebpf
      - grafana

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"
    depends_on:
      - grafana

  ebpf:
    build:
      context: ./ebpf
      dockerfile: Dockerfile_ebpf
    privileged: true

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - frontend
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
