version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"
    depends_on:
      - ebpf

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"

  ebpf:
    build:
      context: ./ebpf
      dockerfile: Dockerfile_ebpf
    privileged: true
    
