FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:longsleep/golang-backports -y && \
    apt-get update && \
    apt-get install -y python3 python3-pip bcc bpfcc-tools

WORKDIR /app

COPY backend.py .

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "backend.py"]

