FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip bpfcc-tools libbpfcc0=0.17.0-2

WORKDIR /app

COPY backend.py .

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "backend.py"]
