FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y bpfcc-tools libbpfcc

COPY metrics_ebpf.c /app/metrics_ebpf.c

RUN cd /app && \
    clang -O2 -target bpf -c metrics_ebpf.c -o metrics_ebpf.o

CMD ["ip", "link", "set", "up", "dev", "lo", "&&", "bpftool", "prog", "load", "/app/metrics_ebpf.o", "/sys/fs/bpf/metrics_ebpf"]
